# Generated by Django 4.0.5 on 2022-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='book_images')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
