# Generated by Django 4.0.5 on 2022-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
