# Generated by Django 4.0.5 on 2022-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylib', '0004_remove_book_quantity_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
