# Generated by Django 4.0.3 on 2022-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylib', '0005_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bookpdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book_images'),
        ),
    ]
